
SRC = app/main.cpp strategy/TeamATimeEstimator.cpp strategy/TeamBTimeEstimator.cpp \
	strategy/QualityFirstDeadlineEstimator.cpp strategy/SpeedFirstDeadlineEstimator.cpp


.PHONY: all

all: a.out
a.out:
	g++ $(SRC) -o uzd1
