
SRC = app/main.cpp strategy/TeamATimeEstimator.cpp strategy/TeamBTimeEstimator.cpp \
	strategy/QualityFirstDeadlineEstimator.cpp strategy/SpeedFirstDeadlineEstimator.cpp \
	tm/TM_QualityFirstDeadlineEstimator.cpp tm/TM_QualityFirstTeamADeadlineEstimator.cpp \
	tm/TM_QualityFirstTeamBDeadlineEstimator.cpp tm/TM_SpeedFirstDeadlineEstimator.cpp \
	tm/TM_SpeedFirstTeamADeadlineEstimator.cpp tm/TM_SpeedFirstTeamBDeadlineEstimator.cpp


.PHONY: all

all: a.out
a.out:
	g++ $(SRC) -o uzd1
